url = 'https://fr.openfoodfacts.org/cgi/search.pl'
connexion = "mysql+pymysql://testeur:camomille@localhost/test?charset=utf8mb4"
directory = "sql"
create_table = 'drop_create.sql'
insert_data = 'insert_product.sql'
ngrad_a = 'A'
ngrad_b = 'B'
ngrad_c = 'C'
ngrad_d = 'D'
ngrad_e = 'E'
categories = ['pizza', 'steack hache', 'pates a tartiner', 'creme glacee', 'soda']
cat1 = 'pizza'
cat2 = 'steack hache'
cat3 = 'pates a tartiner'
cat4 = 'creme glacee'
cat5 = 'soda'
num_cat1 = 1
num_cat2 = 2
num_cat3 = 3
num_cat4 = 4
num_cat5 = 5
rds_prod = """INSERT INTO product (code, name, brand, url, nutriscore) VALUES (:code, :name, :brand, :url, :nutriscore)"""
